on:
    workflow_dispatch:
      inputs:
        repositorio:
          description: 'Nombre del repositorio'
          required: true

name: CD
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Set up  QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up  Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: rguerreropiuraperu/firstaction-reiniciowindows:${{github.sha}}